package token

type Kind string

const (
	ILLEGAL Kind = "ILLEGAL"
	EOF     Kind = "EOF"

	IDENT       Kind = "IDENT"
	NUMBER      Kind = "NUMBER"
	STRING      Kind = "STRING"
	CHAR        Kind = "CHAR"
	BYTE_CHAR   Kind = "BYTE_CHAR"
	DOC_COMMENT Kind = "DOC_COMMENT"

	ASSIGN       Kind = "="
	PLUS         Kind = "+"
	MINUS        Kind = "-"
	ASTERISK     Kind = "*"
	SLASH        Kind = "/"
	PERCENT      Kind = "%"
	PLUS_ASSIGN  Kind = "+="
	MINUS_ASSIGN Kind = "-="
	STAR_ASSIGN  Kind = "*="
	SLASH_ASSIGN Kind = "/="
	PCT_ASSIGN   Kind = "%="
	PLUS_PLUS    Kind = "++"
	MINUS_MINUS  Kind = "--"
	BANG         Kind = "!"
	QUESTION     Kind = "?"
	AT           Kind = "@"
	AMP          Kind = "&"
	TILDE        Kind = "~"
	LT           Kind = "<"
	GT           Kind = ">"
	EQ           Kind = "=="
	NEQ          Kind = "!="
	LE           Kind = "<="
	GE           Kind = ">="
	ANDAND       Kind = "&&"
	OROR         Kind = "||"
	BAR          Kind = "|"
	PIPE_ARROW   Kind = "|>"
	CARET        Kind = "^"
	CARET_ASSIGN Kind = "^="
	QQ           Kind = "??"
	BB           Kind = "!!"
	FATARROW     Kind = "=>"
	ARROW        Kind = "->"
	COLON        Kind = ":"
	DCOLON       Kind = "::"
	COMMA        Kind = ","
	DOT          Kind = "."
	DOTDOT       Kind = ".."
	DOTDOT_EQ    Kind = "..="
	ELLIPSIS     Kind = "..."
	HASH         Kind = "#"
	SEMICOLON    Kind = ";"

	LPAREN Kind = "("
	RPAREN Kind = ")"
	LBRACE Kind = "{"
	RBRACE Kind = "}"
	LBRACK Kind = "["
	RBRACK Kind = "]"

	IMPORT    Kind = "IMPORT"
	CONST     Kind = "CONST"
	TYPE      Kind = "TYPE"
	STRUCT    Kind = "STRUCT"
	INTERFACE Kind = "INTERFACE"
	ENUM      Kind = "ENUM"
	UNION     Kind = "UNION"
	ERROR     Kind = "ERROR"
	FN        Kind = "FN"
	TEST      Kind = "TEST"
	LET       Kind = "LET"
	IF        Kind = "IF"
	ELSE      Kind = "ELSE"
	MATCH     Kind = "MATCH"
	FOR       Kind = "FOR"
	WHILE     Kind = "WHILE"
	BREAK     Kind = "BREAK"
	CONTINUE  Kind = "CONTINUE"
	RETURN    Kind = "RETURN"
	AS        Kind = "AS"
	IS        Kind = "IS"
	MUT       Kind = "MUT"
	ATOMIC    Kind = "ATOMIC"
	COMPTIME  Kind = "COMPTIME"
	LOCK      Kind = "LOCK"
	DEFER     Kind = "DEFER"
	PANIC     Kind = "PANIC"
	RELEASE   Kind = "RELEASE"
	CATCH     Kind = "CATCH"
	NONE      Kind = "NONE"
	UNSAFE    Kind = "UNSAFE"
	IMPL      Kind = "IMPL"
)
