package token

type Kind string

const (
	ILLEGAL Kind = "illegal"
	EOF     Kind = "end of file"

	IDENT       Kind = "identifier"
	NUMBER      Kind = "number"
	STRING      Kind = "string"
	CHAR        Kind = "charecter"
	BYTE_CHAR   Kind = "byte character"
	DOC_COMMENT Kind = "document comment"

	ASSIGN       Kind = "="
	PLUS         Kind = "+"
	MINUS        Kind = "-"
	ASTERISK     Kind = "*"
	SLASH        Kind = "/"
	PERCENT      Kind = "%"
	PLUS_ASSIGN  Kind = "+="
	MINUS_ASSIGN Kind = "-="
	STAR_ASSIGN  Kind = "*="
	SLASH_ASSIGN Kind = "/="
	PCT_ASSIGN   Kind = "%="
	PLUS_PLUS    Kind = "++"
	MINUS_MINUS  Kind = "--"
	BANG         Kind = "!"
	QUESTION     Kind = "?"
	AT           Kind = "@"
	AMP          Kind = "&"
	TILDE        Kind = "~"
	LT           Kind = "<"
	GT           Kind = ">"
	EQ           Kind = "=="
	NEQ          Kind = "!="
	LE           Kind = "<="
	GE           Kind = ">="
	ANDAND       Kind = "&&"
	OROR         Kind = "||"
	BAR          Kind = "|"
	PIPE_ARROW   Kind = "|>"
	CARET        Kind = "^"
	CARET_ASSIGN Kind = "^="
	QQ           Kind = "??"
	BB           Kind = "!!"
	FATARROW     Kind = "=>"
	ARROW        Kind = "->"
	COLON        Kind = ":"
	DCOLON       Kind = "::"
	COMMA        Kind = ","
	DOT          Kind = "."
	DOTDOT       Kind = ".."
	DOTDOT_EQ    Kind = "..="
	ELLIPSIS     Kind = "..."
	HASH         Kind = "#"
	SEMICOLON    Kind = ";"

	LPAREN Kind = "("
	RPAREN Kind = ")"
	LBRACE Kind = "{"
	RBRACE Kind = "}"
	LBRACK Kind = "["
	RBRACK Kind = "]"

	IMPORT    Kind = "import"
	CONST     Kind = "constant"
	TYPE      Kind = "type"
	STRUCT    Kind = "struct"
	INTERFACE Kind = "interaface"
	ENUM      Kind = "enum"
	UNION     Kind = "union"
	ERROR     Kind = "error"
	FN        Kind = "function"
	TEST      Kind = "test"
	LET       Kind = "let"
	IF        Kind = "if"
	ELSE      Kind = "else"
	MATCH     Kind = "match"
	FOR       Kind = "for"
	WHILE     Kind = "while"
	BREAK     Kind = "break"
	CONTINUE  Kind = "continue"
	RETURN    Kind = "return"
	AS        Kind = "as"
	IS        Kind = "is"
	MUT       Kind = "mut"
	ATOMIC    Kind = "atomic"
	COMPTIME  Kind = "comptime"
	LOCK      Kind = "lock"
	DEFER     Kind = "defer"
	PANIC     Kind = "panic"
	RELEASE   Kind = "release"
	CATCH     Kind = "catch"
	NONE      Kind = "none"
	UNSAFE    Kind = "unsafe"
	IMPL      Kind = "impl"
)
